### ISSUE TITLE
Filled out pdf forms get lost when uniting

### ISSUE THREAD

**Issue by pianoslum** [mtgrosser/pdfunite#2]
Hi, thanks for the nice tool.
Yesterday I tried to unite a pdf with a filled out form. In the result, all the changes were missing.
Using pdftk worked.

Unfortunately, I cannot attach the pdf I used, but maybe the feature is not implemented?

**Comment by mtgrosser** [comment]
This is caused by `poppler`. Maybe you check out [boazsegev/combine_pdf](https://github.com/boazsegev/combine_pdf), it's a pure Ruby lib without external dependencies.

**Comment by pianoslum** [comment]
If this is known and accepted it's fine by me :)
As I wrote pdftk also works with forms.
